{
    "name": "ISIC - Site Institutionnel",
    "summary": "Site web institutionnel de l'ISIC avec blog integre",
    "version": "19.0.1.0.0",
    "category": "Website",
    "author": "ISIC Rabat",
    "website": "https://isic.ac.ma",
    "license": "Other proprietary",
    "depends": ["website", "website_blog", "isic_theme_website"],
    "data": [
        # Menus & blog data
        "data/website_menu_data.xml",
        "data/blog_data.xml",
        # Templates
        "views/templates/layout.xml",
        "views/templates/home.xml",
        "views/templates/institut.xml",
        "views/templates/formations.xml",
        "views/templates/vie_etudiante.xml",
        "views/templates/recherche.xml",
        "views/templates/contact.xml",
        "views/templates/blog_override.xml",
    ],
    "assets": {
        "web.assets_frontend": [
            "isic_website/static/src/scss/variables.scss",
            "isic_website/static/src/scss/layout.scss",
            "isic_website/static/src/scss/components.scss",
            "isic_website/static/src/scss/pages/home.scss",
            "isic_website/static/src/scss/pages/institut.scss",
            "isic_website/static/src/scss/pages/formations.scss",
            "isic_website/static/src/scss/pages/vie_etudiante.scss",
            "isic_website/static/src/scss/pages/recherche.scss",
            "isic_website/static/src/scss/pages/contact.scss",
            "isic_website/static/src/scss/pages/blog.scss",
            "isic_website/static/src/scss/animations.scss",
            "isic_website/static/src/scss/responsive.scss",
            "isic_website/static/src/js/website_interactions.js",
        ],
    },
    "post_init_hook": "_post_init_cleanup",
    "installable": True,
    "application": False,
}
